config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :links
  root "pages#home"

  get "/api/links/exists", to: "links#link_exists", defaults: { format: 'json' }
  put "/api/links/:id/favorite", to: "links#favorite", defaults: { format: 'json' }
  put "/api/links/:id/unfavorite", to: "links#unfavorite", defaults: { format: 'json' }
  get "/my_links", to: "links#my_links"
  get "/*short", to: "links#redirection"
  

end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id          :integer          not null, primary key
#  destination :string
#  shortened   :string
#  favorited   :integer          default([]), is an Array
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Link < ActiveRecord::Base
  require 'uri' # For checking if a URL is valid
  validates :destination, url: true
  validates :shortened, uniqueness: true, allow_nil: true
  validates :shortened, length: { minimum: 4, maximum: 12 }, allow_blank: true
  validates :title, presence: true
  belongs_to :user

  # Returns true if the provided url is valid
  def self.is_valid_url(url)
    uri = URI.parse(url)
    uri.kind_of?(URI::HTTP)
    rescue URI::InvalidURIError
      false
  end

  # Generates a random string for a short url
  def self.generate_string
    min_length = 4
    max_length = 12
    generated_string = ""

    characters = ("A".."Z").to_a + ("a".."z").to_a + (0..9).to_a
    num_characters = characters.size - 1
    length = Random.rand(min_length..max_length)

    length.times do |i|
      character = characters[Random.rand(0..num_characters)].to_s
      generated_string += character
    end

    return generated_string
  end

  # Sets self.shortened to a unique string
  def assign_unique_shortened_string
    shortened = Link.generate_string
    self.shortened = shortened

    while not self.save
      shortened = Link.generate_string
      self.shortened = shortened
    end
  end

  # Returns the title of this link
  def get_title
    title = self.title

    if title.nil?
      return ""
    else
      return title
    end
  end

  # Returns the description of this link
  def get_description
    description = self.description

    if description.nil?
      return ""
    else
      return description
    end
  end

  # Returns the short url of this link
  def get_shorturl(root_path)
    path = self.shortened
    base = root_path
    shorturl = base + path
    return shorturl
  end

  # Returns the full url of this link
  def get_url
    url = self.destination
    return url
  end

  # Returns the number of times this url has been favorited
  def get_favorite_count
    favorites = self.favorited
    favorite_count = favorites.size
    return favorite_count
  end

  # Returns the list of users who have favorited this link
  def get_favorited_users
    user_ids = self.favorited
    if user_ids.empty?
      return "None"
    else
      users = ""

      user_ids.each do |user_id|
        user = User.find_by(id: user_id)

        if not user.nil?
          users += user.name + ", "
        end
      end

      if users.size > 0
        users = users[0, users.size - 2]
      end

      return users
    end
  end

  # Returns the user who owns this link
  def get_user
    return self.user.name
  end

  # Returns true if this link belongs to the specified user
  def belongs_to_user(user_id)
    return self.user.id == user_id
  end

  # Add this link to the specified user's favorites
  def favorite(user_id)
    user = User.find_by(id: user_id)

    if not user.nil? and not user.favorites.include? self.id
      user.favorites << self.id
      user.save
      self.favorited << user.id
      self.save
      puts "Added link# #{self.id} to user# #{user_id}'s favorites"
    end
  end

  # Remove this link from the specified user's favorites
  def unfavorite(user_id)
    user = User.find_by(id: user_id)

    if not user.nil? and user.favorites.include? self.id
      user.favorites.delete(self.id)
      user.save
      self.favorited.delete(user.id)
      self.save
      puts "Removed link# #{self.id} from user# #{user_id}'s favorites"
    else
      puts "Couldn't remove link# #{self.id} to user# #{user_id}'s favorites"
    end
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :redirection]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # show my links page
  def my_links
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        if @link.shortened.nil? or @link.shortened.empty?
          @link.assign_unique_shortened_string
          @link.save
        end
        current_user.links << @link
        current_user.save

        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Checks to see if the link data already exists in the database
  # GET /api/links/exists
  # Testing via curl: curl -H "Content-Type: application/json" -X GET -d '{ "destination": "https://www.google.com" }' http://localhost:3000/api/links/exists
  def link_exists
    status = -1
    errors = []
    destination = params["destination"]
    json_response = {}

    if destination.nil?
      errors << "Error: you must provide a destination"
    else
      links = Link.where(destination: destination)
      if links.empty? or links.nil?
        status = 1
      else
        errors << "Error: that link already exists in the database"
      end
    end

    if status == -1
      json_response["errors"] = errors
    end

    json_response["status"] = status
    json_response = json_response.to_json

    respond_to do |format|
      format.json { render json: json_response }
    end
  end

  # Adds the link to the user's favorites
  # PUT /api/links/:id/favorite
  # Testing via curl: curl -H "Content-Type: application/json" -X PUT -d '{ "user_id": 1, "link_id": 21 }' http://localhost:3000/api/links/21/favorite
  def favorite
    status = -1
    errors = []
    user_id = params["user_id"]
    link_id = params[:id]
    json_response = {}

    if user_id.nil?
      errors << "Error: you must provide a user_id"
    elsif link_id.nil?
      errors << "Error: you must provide a link_id"
    else
      link = Link.find_by(id: link_id)
      user = User.find_by(id: user_id)

      if link.nil?
        errors << "Error: no link with id #{link_id} exists"
      elsif user.nil?
        errors << "Error: no user with id #{user_id} exists"
      else
        link.favorite(user_id)
        status = 1
      end
    end

    if status == -1
      json_response["errors"] = errors
    end

    json_response["status"] = status
    json_response = json_response.to_json

    respond_to do |format|
      format.json { render json: json_response }
    end
  end

  # Removes the link from the user's favorites
  # PUT /api/links/:id/favorite
  # Testing via curl: curl -H "Content-Type: application/json" -X PUT -d '{ "user_id": 1 }' http://localhost:3000/api/links/21/unfavorite
  def unfavorite
    status = -1
    errors = []
    user_id = params["user_id"]
    link_id = params[:id]
    json_response = {}

    puts "UNFAVORITING IN FUNCTION"

    if user_id.nil?
      errors << "Error: you must provide a user_id"
    elsif link_id.nil?
      errors << "Error: you must provide a link_id"
    else
      link = Link.find_by(id: link_id)
      user = User.find_by(id: user_id)

      if link.nil?
        errors << "Error: no link with id #{link_id} exists"
      elsif user.nil?
        errors << "Error: no user with id #{user_id} exists"
      else
        puts "UNFAVORITING"
        link.unfavorite(user_id)
        status = 1
      end
    end

    if status == -1
      json_response["errors"] = errors
    end

    json_response["status"] = status
    json_response = json_response.to_json

    respond_to do |format|
      format.json { render json: json_response }
    end
  end

  # Redirect a short url to its actual destination
  def redirection
    short = params["short"]

    if short.nil?
      redirect_to root_url
    else
      link = Link.find_by(shortened: short)

      if link.nil?
        redirect_to root_url
      else
        redirect_to link.destination
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:destination, :shortened, :favorited, :description, :title)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :short_path %><br>
    <%= f.text_field :shortened %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit class: "pretty_button" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Back', @link %> |
<%= link_to 'All Links', links_path %> |
<%= link_to 'Delete', link_path(@link), data: { confirm: 'Are you sure?' }, method: :delete %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">All Links</h1>

<table id="user-links-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>URL</th>
      <th>Shortlink</th>
      <th>Favorites</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr class="clickable-row" data-href="<%= link_url(link) %>">
        <td><%= link.get_title %></td>
        <td><%= link_to(link.get_url, link.get_url, target: "_blank") %></td>
        <td><%= link_to(link.get_shorturl(root_url), link.get_shorturl(root_url), target: "_blank") %></td>
        <td><%= link.get_favorite_count %></td>
        <td><%= link.get_user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/links/my_links.html.erb
<h1 class="title">My Links</h1>

<% if current_user.links.empty? %>
  <p>Looks like you don't have any links yet. Why not <%= link_to("create one", root_url) %>?</p>
<% else %>
  <table id="user-links-table">
    <thead>
      <tr>
        <th>Title</th>
        <th>URL</th>
        <th>Shortlink</th>
        <th>Favorites</th>
      </tr>
    </thead>

    <tbody>
      <% current_user.links.each do |link| %>
        <tr class="clickable-row" data-href="<%= link_url(link) %>">
          <td><%= link.get_title %></td>
          <td><%= link_to(link.get_url, link.get_url, target: "_blank") %></td>
          <td><%= link_to(link.get_shorturl(root_url), link.get_shorturl(root_url), target: "_blank") %></td>
          <td><%= link.get_favorite_count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<h1 class="title">My Favorite Links</h1>

<% if current_user.favorites.empty? %>
  <p>You currently have no favorite links.</p>
<% else %>
  <table id="favorite-links-table">
    <thead>
      <tr>
        <th>Title</th>
        <th>URL</th>
        <th>Shortlink</th>
        <th>User</th>
      </tr>
    </thead>

    <tbody>
      <% current_user.favorite_links.each do |link| %>
        <tr class="clickable-row" data-href="<%= link_url(link) %>">
          <td><%= link.get_title %></td>
          <td><%= link_to(link.get_url, link.get_url, target: "_blank") %></td>
          <td><%= link_to(link.get_shorturl(root_url), link.get_shorturl(root_url), target: "_blank") %></td>
          <td><%= link.user.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Viewing Link: "<%= @link.get_title %>"
  <span id="favorited">
  <% if current_user.has_favorited(@link.id)%>
    (Favorited)
  <% end %>
  </span>
</h1>

<p>
  <strong>Destination:</strong>
  <%= link_to(@link.get_url, @link.get_url, target: "_blank") %>
</p>

<p>
  <strong>Shortly URL:</strong>
  <%= link_to(@link.get_shorturl(root_url), @link.get_shorturl(root_url), target: "_blank") %>
</p>

<% if not @link.belongs_to_user(current_user.id) %>
  <p>
    This link was created by <%= @link.get_user %>.
  </p>

  <% if current_user.has_favorited(@link.id) %>
    <button class="favorite_button pretty_button" type="button" onclick="unfavorite(<%= @link.id %>, <%= current_user.id %>)">Remove This Link From Your Favorites</button>
  <% else %>
    <button class="favorite_button pretty_button" type="button" onclick="favorite(<%= @link.id %>, <%= current_user.id %>)">Favorite This Link!</button>
  <% end %>
<% else %>
  <p>
    <%= link_to 'Edit this link', edit_link_path(@link) %>
  </p>
<% end %>