config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :links
  root "pages#home"

  get "/api/links/exists", to: "links#link_exists", defaults: { format: 'json' }
  put "/api/links/:id/favorite", to: "links#favorite", defaults: { format: 'json' }
  put "/api/links/:id/unfavorite", to: "links#unfavorite", defaults: { format: 'json' }
  get "/my_links", to: "links#my_links"
  get "/*short", to: "links#redirection"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shortly</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.10/css/jquery.dataTables.css">
  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.10/js/jquery.dataTables.js"></script>
</head>
<body>
  <header>
    <div id="logo">
      <%= link_to("Short", root_url) %><span class='orange'><%= link_to("ly", root_url) %></span>
    </div>
    <nav>
      <ul>
        <li><%= link_to("Home", root_url) %></li>
        <li><%= link_to("All Links", links_url) %></li>
        <% if user_signed_in? %>
          <li><%= link_to("Account", edit_user_registration_path(self)) %></li>
          <li><%= link_to("My Links", my_links_path) %></li>
          <li><%= link_to("Sign out", destroy_user_session_path, method: :delete) %></li>
        <% else %>
          <li><%= link_to("Sign in", new_user_session_path) %></li>
          <li><%= link_to("Sign up", new_user_registration_path) %></li>
        <% end %>
      </ul>
    </nav>
  </header>
  <div id="content">
    <%= yield %>
  </div>
</body>
</html>